### ISSUE TITLE
请问项目中涉及到的表结构的sql语句可以一并提供到仓库内？

### ISSUE THREAD

**Issue by zhailuxu** [zzq0324/alarm-bot#3]
请问项目中涉及到的表结构的sql语句可以一并提供到仓库内？

**Comment by zzq0324** [comment]
> 请问项目中涉及到的表结构的sql语句可以一并提供到仓库内？

@zhailuxu 不好意思，漏说明了。数据库初始化语句详见[init.sql](https://raw.githubusercontent.com/zzq0324/alarm-bot/main/docs/init.sql)，你先看下

**Comment by zhailuxu** [comment]
你好，init.sql内容应该不是最新的，比如member表缺少了identity字段，辛苦更新下init.sql哈，谢谢

**Comment by zzq0324** [comment]
> 你好，init.sql内容应该不是最新的，比如member表缺少了identity字段，辛苦更新下init.sql哈，谢谢

Sorry，上次更新字段做了调整，漏同步了。已修正，谢谢您的反馈
