### ISSUE TITLE
请问这个项目只支持发送者的idType是app_id的，不支持是open_id的？

### ISSUE THREAD

**Issue by zhailuxu** [zzq0324/alarm-bot#4]
请问这个项目只支持发送者的idType是app_id的，不支持是open_id的？为啥做这个限制？我该了下代码，测试idType=open_id时也是可以实现功能的

**Comment by zzq0324** [comment]
> 请问这个项目只支持发送者的idType是app_id的，不支持是open_id的？为啥做这个限制？我该了下代码，测试idType=open_id时也是可以实现功能的

具体哪个接口或者方法呢

**Comment by zhailuxu** [comment]
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/10771114/159828962-14a39734-dbe7-4bce-8e58-539ed3e650f8.png">

**Comment by zzq0324** [comment]
> <img alt="image" width="1007" src="https://user-images.githubusercontent.com/10771114/159828962-14a39734-dbe7-4bce-8e58-539ed3e650f8.png">
> 
> 如图103行

明白你的意思了。alarm-bot在设计的时候支持两种IM消息：

1. 非机器人发送：非机器人在群里发送告警信息（例如人发送的），此时飞书官方会直接回调，alarm-bot收到回调之后就会执行对应的处理逻辑，此时不会经过[LarkRobotHookMessageScanner.java](https://github.com/zzq0324/alarm-bot/blob/main/alarm-bot-web/src/main/java/cn/zzq0324/alarm/bot/web/task/LarkRobotHookMessageScanner.java)。前提是已经订阅了相关的飞书事件和权限，详见[飞书配置](https://alarm-bot.zzq0324.cn/#/deploy-lark)；
2. 机器人发送：机器人发送的消息官方不会回调，因此增加了[LarkRobotHookMessageScanner.java](https://github.com/zzq0324/alarm-bot/blob/main/alarm-bot-web/src/main/java/cn/zzq0324/alarm/bot/web/task/LarkRobotHookMessageScanner.java)来获取机器人发送的消息，机器人发送的话sender一定是会包含app_id。

在我们的场景里，告警群里会有两个机器人，一个是群里直接添加的机器人A，另一个是Alarm Bot机器人。告警信息会先通过机器人A的WebHook URL推送告警信息群，由于此时Alarm Bot机器人收不到机器人A的回调信息，因此就走定时任务的方式来爬信息处理。

**Comment by zzq0324** [comment]
> > <img alt="image" width="1007" src="https://user-images.githubusercontent.com/10771114/159828962-14a39734-dbe7-4bce-8e58-539ed3e650f8.png">
> > 如图103行
> 
> 明白你的意思了。alarm-bot在设计的时候支持两种IM消息：
> 
> 1. 非机器人发送：非机器人在群里发送告警信息（例如人发送的），此时飞书官方会直接回调，alarm-bot收到回调之后就会执行对应的处理逻辑，此时不会经过[LarkRobotHookMessageScanner.java](https://github.com/zzq0324/alarm-bot/blob/main/alarm-bot-web/src/main/java/cn/zzq0324/alarm/bot/web/task/LarkRobotHookMessageScanner.java)。前提是已经订阅了相关的飞书事件和权限，详见[飞书配置](https://alarm-bot.zzq0324.cn/#/deploy-lark)；
> 2. 机器人发送：机器人发送的消息官方不会回调，因此增加了[LarkRobotHookMessageScanner.java](https://github.com/zzq0324/alarm-bot/blob/main/alarm-bot-web/src/main/java/cn/zzq0324/alarm/bot/web/task/LarkRobotHookMessageScanner.java)来获取机器人发送的消息，机器人发送的话sender一定是会包含app_id。
> 
> 在我们的场景里，告警群里会有两个机器人，一个是群里直接添加的机器人A，另一个是Alarm Bot机器人。告警信息会先通过机器人A的WebHook URL推送告警信息群，由于此时Alarm Bot机器人收不到机器人A的回调信息，因此就走定时任务的方式来爬信息处理。
> 
> 你是通过直接@Alarm Bot的方式做测试吗？如果是的话飞书开发者后台相关的事件和回调开启即可。

补充下，通过回调的时效会比[LarkRobotHookMessageScanner.java](https://github.com/zzq0324/alarm-bot/blob/main/alarm-bot-web/src/main/java/cn/zzq0324/alarm/bot/web/task/LarkRobotHookMessageScanner.java)高，因此非机器人发送的还是走回调处理，机器人回调的才走[LarkRobotHookMessageScanner.java](https://github.com/zzq0324/alarm-bot/blob/main/alarm-bot-web/src/main/java/cn/zzq0324/alarm/bot/web/task/LarkRobotHookMessageScanner.java)特殊处理（不知道飞书为啥不回调机器人信息，不然是不需要这个判断）。

**Comment by zhailuxu** [comment]
感谢解答

**Comment by zhailuxu** [comment]
建议使用文档上，补充下这两种场景哈，

**Comment by zhailuxu** [comment]
发现项目中用到了飞书开发平台的官方SDK，请问这个SDK使用上有什么不便的地方？或者有更好的建议也欢迎提供下哈。

**Comment by zzq0324** [comment]
> 发现项目中用到了飞书开发平台的官方SDK，请问这个SDK使用上有什么不便的地方？或者有更好的建议也欢迎提供下哈。

使用上还好，没啥不方便的，就是sdk的更新速度不够快有些能力没有实现方法
